name: CI - Validation

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Validate
    runs-on: x86_64_monterey
    steps:
      - uses: actions/checkout@v3
      - name: Validate
        run: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 OpenCore-Patcher-GUI.command --validate
